

ajax_form_validation:
    formats:
        default:
            postCode: '[0-9\-\ ]+'
            phone: '\+?[0-9\-\ ]+'
            city: '[\p{L}\ 0-9\-]+'
            street: '[\p{L}\ 0-9\-\.\:]+'
            url: '((http|ftp|https)?:\/\/)?[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%%&amp;:\/\+#]*[\w\-\@?^=%%&amp;\/\+#])?'
        fr:
            postCode: '[0-9]{5}'
            phone: '\+?(33)?[\ \-]?([0-9\-\ ]{4,12})'
        pl:
            postCode: '[0-9]{1}\-[0-9]{3}'
            phone: '\+?(48)?[\ \-]?([0-9\-\ ]{4,12})'