services:
    validator.configs:
        class: AjaxFormValidationBundle\Service\LocalizedConfigs
        arguments:
            - ~
            - %locale%
    validator.form.type.gender:
        class: AjaxFormValidationBundle\Form\GenderForm
        arguments:
            - '@validator.configs'
            - '%locale%'
            - '@translator'
        tags:
            - { name: 'form.type', alias: gender }
    validator.form.type.post_code:
        class: AjaxFormValidationBundle\Form\PostCodeForm
        arguments:
            - '@validator.configs'
            - '%locale%'
            - '@translator'
        tags:
            - { name: 'form.type', alias: postCode }
    validator.form.type.phone:
        class: AjaxFormValidationBundle\Form\PhoneForm
        arguments:
            - '@validator.configs'
            - '%locale%'
            - '@translator'
        tags:
            - { name: 'form.type', alias: phone }
    validator.form.type.url:
        class: AjaxFormValidationBundle\Form\UrlForm
        arguments:
            - '@validator.configs'
            - '%locale%'
            - '@translator'
        tags:
            - { name: 'form.type', alias: url }
    validator.form.type.city:
        class: AjaxFormValidationBundle\Form\CityForm
        arguments:
            - '@validator.configs'
            - '%locale%'
            - '@translator'
        tags:
            - { name: 'form.type', alias: city }
    validator.form.type.street:
        class: AjaxFormValidationBundle\Form\StreetForm
        arguments:
            - '@validator.configs'
            - '%locale%'
            - '@translator'
        tags:
            - { name: 'form.type', alias: street }
    validator.form.type.password:
        class: AjaxFormValidationBundle\Form\PasswordForm
        arguments:
            - '@validator.configs'
            - '%locale%'
            - '@translator'
        tags:
            - { name: 'form.type', alias: password }
    validator.form.type.password_confirm:
        class: AjaxFormValidationBundle\Form\PasswordConfirmForm
        arguments:
            - '@validator.configs'
            - '%locale%'
            - '@translator'
        tags:
            - { name: 'form.type', alias: password_confirm }
    validator.form.type.name:
        class: AjaxFormValidationBundle\Form\NameForm
        arguments:
            - '@validator.configs'
            - '%locale%'
            - '@translator'
        tags:
            - { name: 'form.type', alias: name }